### ISSUE TITLE
Enable user fast charger and slow charger selection

### ISSUE THREAD

**Issue by CBNU-kimjimin** [IllllIIlI/ProjPrac#19]
Please give me your opinion on how to implement the function.

**Comment by IllllIIlI** [comment]
Receive input between Fast, Slow, and No Problem
If it's No Problem, proceed with the next step with the Excel that was extracted before
Fast or slow, the number of chargers in Excel is 1, 2, 3... Obtain 9 Excel files each. This is because the maximum number of chargers in the charging station is 9. And put the Excel files back together
